spring:
  config:
    import: optional:configserver:http://confi-server-svc:8888
  application:
    name: product-service

openapi:
  service:
    title: product-service doc
    version: 1.0.0
    url: http://product-svc:8050

springdoc:
  api-docs:
    path: /api/v1/products/v3/api-docs
  swagger-ui:
    path: /api/v1/products/swagger-ui.html



