spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: customer-service


openapi:
  service:
    title: customer-service doc
    version: 1.0.0
    url: http://localhost:8090

springdoc:
  api-docs:
    path: /api/v1/customers/v3/api-docs
  swagger-ui:
    path: /api/v1/customers/swagger-ui.html
