name: notification service API Pipeline

on:
  push:
    branches: 
      - main
    paths:
      - 'services/notification/**'
  pull_request:
    branches: 
      - main
    paths:
      - 'services/notification/**'
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest
    name: Compile notification service
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Compile notification
        run: |
         cd services/notification
         mvn clean compile
  unit-tests:
    runs-on: ubuntu-latest
    name: Unit tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Running Unit Tests
        run: |
          cd services/notification 
          mvn clean test


  build:
    runs-on: ubuntu-latest
    name: Build backend
    needs: [ compile ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: Build project
        run: |
          cd services/notification 
          mvn clean package -DskipTests
          

  build-image:
     name: Build Docker image
     runs-on: ubuntu-latest
     needs: [ build ]
     steps:
       - name: Setup JDK
         uses: actions/setup-java@v4
         with:
           java-version: '17'
           distribution: 'corretto'

       - name: Login to DockerHub
         uses: docker/login-action@v3
         with:
           username: ${{ secrets.DOCKERHUB_USERNAME }}
           password: ${{ secrets.DOCKERHUB_TOKEN }}

       - name: Build & Push to DockerHub
         uses: docker/build-push-action@v5
         with:
           file: docker/notification/Dockerfile
           push: true
           platforms: linux/amd64
           tags: ${{ secrets.DOCKERHUB_USERNAME }}/notification:latest
           
            
